# Generated by Django 2.2.5 on 2020-12-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_auto_20201230_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
    ]
